// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
/**
 * Per-instance operator README generation. Contains the real manager commands
 * for this installed version, paths, and URLs. Never contains secrets.
 */
import type { InstanceManifest } from '@shm/schemas';
import { instancePaths } from './paths.js';

export interface ReadmeOptions {
  managerVersion: string;
  root: string;
}

export function generateInstanceReadme(manifest: InstanceManifest, opts: ReadmeOptions): string {
  const id = manifest.instanceId;
  const p = instancePaths(id, opts.root);
  const dir = p.dir;

  return `# SelfHelp instance: ${manifest.displayName} (\`${id}\`)

Generated by SelfHelp Manager ${opts.managerVersion}. Do not edit by hand.

## Summary

- Public URL: ${manifest.routing.publicFrontendUrl}
- Instance id: \`${id}\`
- Display name: ${manifest.displayName}
- Mode: ${manifest.mode}
- SelfHelp version: ${manifest.versions.selfhelp}
- Compose project: \`selfhelp_${id}\`
- Manifest: \`${p.manifestPath}\`
- Lock file: \`${p.lockPath}\`
- Compose file: \`${p.composePath}\`
- Backups: \`${p.backupsDir}\`
- Support bundles / logs: \`${p.logsDir}\`

> Secrets live in \`${p.secretsDir}\` with restrictive permissions and are intentionally not printed here.

## Everyday commands

\`\`\`bash
cd ${dir} && docker compose up -d
cd ${dir} && docker compose down
cd ${dir} && docker compose restart
cd ${dir} && docker compose logs -f --tail=200
\`\`\`

## Manager commands

\`\`\`bash
sh-manager instance health ${id}
sh-manager instance backup ${id}
sh-manager instance update --dry-run ${id}
sh-manager instance update ${id}
sh-manager instance support-bundle ${id}
sh-manager instance safe-mode enable ${id}
sh-manager instance restore ${id} <backupId>
\`\`\`

## Health endpoint

- Backend readiness: \`${manifest.routing.publicFrontendUrl}${manifest.routing.browserApiPrefix}/cms-api/v1/health\` (via the BFF)

## Update notes

- The CMS admin UI can request/monitor updates for **this instance only**.
- Docker/image/config/migration changes are executed by SelfHelp Manager.
- Updates preserve the database, uploads, plugin artifacts, secrets, backups, and logs.
`;
}
