// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
/**
 * Safe-operation framework for the persistent manager GUI and the CMS
 * operations poller (Workstream 2 Phase A):
 *
 * - {@link OperationJournal} — file-backed journal, one JSON per operation
 *   under `<root>/manager/operations/<opId>.json` (status, phase, timestamps,
 *   REDACTED log lines, result). The GUI polls these records for live logs.
 * - {@link AuditLog} — append-only JSONL at `<root>/manager/audit.jsonl`
 *   (operator, action, instanceId, opId, source IP, result).
 * - {@link InstanceLocks} — one mutating operation per instance, lockfile
 *   under `<root>/manager/locks/<instanceId>.lock`. GUI actions and the CMS
 *   poller share the same lock so they can never run concurrently.
 * - {@link OperationRunner} — ties the three together and runs long actions
 *   in the background: HTTP routes return `202 { operationId }` immediately.
 *
 * Everything written here may end up on an operator's screen or in a support
 * bundle, so every log line / result / error passes through `@shm/support`
 * redaction before touching disk.
 */
import { mkdir, readdir, readFile, rename, rm, writeFile, appendFile } from 'node:fs/promises';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import { redactObject, redactString } from '@shm/support';

export type OperationKind =
  | 'instance_create'
  | 'instance_update'
  | 'instance_frontend_update'
  | 'instance_backup'
  | 'instance_scheduled_backup'
  | 'instance_backup_prune'
  | 'instance_restore'
  | 'instance_clone'
  | 'instance_set_address'
  | 'instance_set_mailer'
  | 'instance_set_env'
  | 'instance_remove'
  | 'cms_operations_drain';

export type OperationStatus = 'running' | 'succeeded' | 'failed';

export interface OperationRecord {
  id: string;
  kind: OperationKind;
  /** Instance the operation mutates; null for server-level work. */
  instanceId: string | null;
  status: OperationStatus;
  /** Coarse current phase for progress display (e.g. "backup", "migrate"). */
  phase: string;
  startedAt: string;
  finishedAt: string | null;
  /** Redacted, append-only log lines (what the GUI shows live). */
  log: string[];
  /** Redacted structured result, present when status === succeeded. */
  result: unknown;
  /** Redacted failure message, present when status === failed. */
  error: string | null;
}

export interface AuditEntry {
  at: string;
  /** Operator email, or "system" for the background poller. */
  operator: string;
  action: string;
  instanceId: string | null;
  operationId: string | null;
  sourceIp: string | null;
  result: 'started' | 'succeeded' | 'failed' | 'denied';
  detail?: string;
}

export function managerStateDir(root: string): string {
  return path.join(root, 'manager');
}

const MAX_LOG_LINES = 2000;

/** File-backed operation journal. Single-process writers (the web server). */
export class OperationJournal {
  private readonly dir: string;
  private readonly now: () => Date;
  /** Serializes read-modify-write per operation id (append vs complete races). */
  private readonly chains = new Map<string, Promise<void>>();

  constructor(root: string, now: () => Date = () => new Date()) {
    this.dir = path.join(managerStateDir(root), 'operations');
    this.now = now;
  }

  private file(id: string): string {
    // Operation ids are generated by us; refuse anything path-like anyway.
    if (!/^[a-z0-9-]+$/i.test(id)) throw new Error(`Invalid operation id "${id}".`);
    return path.join(this.dir, `${id}.json`);
  }

  /**
   * Atomic write (temp file + rename) so a concurrent reader — the GUI polling
   * `get()`/`list()` while an operation completes — never observes a truncated,
   * half-written record. A plain `writeFile` truncates first, and a poll that
   * lands in that window parses an empty file and 404s the operation.
   */
  private async writeRecordAtomic(file: string, data: string): Promise<void> {
    const tmp = `${file}.${randomBytes(6).toString('hex')}.tmp`;
    await writeFile(tmp, data, 'utf8');
    await rename(tmp, file);
  }

  private chain(id: string, work: () => Promise<void>): Promise<void> {
    const prev = this.chains.get(id) ?? Promise.resolve();
    const next = prev.then(work, work);
    this.chains.set(id, next);
    return next;
  }

  async create(kind: OperationKind, instanceId: string | null): Promise<OperationRecord> {
    await mkdir(this.dir, { recursive: true });
    const at = this.now();
    const stamp = at.toISOString().replace(/[-:T]/g, '').slice(0, 14);
    const record: OperationRecord = {
      id: `op-${stamp}-${randomBytes(4).toString('hex')}`,
      kind,
      instanceId,
      status: 'running',
      phase: 'starting',
      startedAt: at.toISOString(),
      finishedAt: null,
      log: [],
      result: null,
      error: null,
    };
    await this.writeRecordAtomic(this.file(record.id), JSON.stringify(record, null, 2));
    return record;
  }

  private async mutate(id: string, fn: (r: OperationRecord) => void): Promise<void> {
    await this.chain(id, async () => {
      const raw = await readFile(this.file(id), 'utf8');
      const record = JSON.parse(raw) as OperationRecord;
      fn(record);
      await this.writeRecordAtomic(this.file(id), JSON.stringify(record, null, 2));
    });
  }

  async append(id: string, line: string): Promise<void> {
    const at = this.now().toISOString();
    await this.mutate(id, (r) => {
      r.log.push(`[${at}] ${redactString(line)}`);
      if (r.log.length > MAX_LOG_LINES) r.log.splice(0, r.log.length - MAX_LOG_LINES);
    });
  }

  async setPhase(id: string, phase: string): Promise<void> {
    const at = this.now().toISOString();
    await this.mutate(id, (r) => {
      r.phase = phase;
      r.log.push(`[${at}] --- ${redactString(phase)} ---`);
    });
  }

  async complete(id: string, result: unknown): Promise<void> {
    await this.mutate(id, (r) => {
      r.status = 'succeeded';
      r.phase = 'done';
      r.finishedAt = this.now().toISOString();
      r.result = result === undefined ? null : redactObject(result);
    });
  }

  async fail(id: string, error: unknown): Promise<void> {
    await this.mutate(id, (r) => {
      r.status = 'failed';
      r.finishedAt = this.now().toISOString();
      r.error = redactString(error instanceof Error ? error.message : String(error));
    });
  }

  async get(id: string): Promise<OperationRecord | null> {
    try {
      return JSON.parse(await readFile(this.file(id), 'utf8')) as OperationRecord;
    } catch {
      return null;
    }
  }

  /**
   * Startup crash recovery: any record still `running` was orphaned by a
   * previous process that died mid-operation (nothing else writes this dir).
   * Mark it failed so the GUI doesn't show a forever-spinning operation.
   * Call once at boot, before new operations start.
   */
  async recoverInterrupted(): Promise<number> {
    let recovered = 0;
    for (const record of await this.list({ limit: Number.MAX_SAFE_INTEGER })) {
      if (record.status !== 'running') continue;
      await this.mutate(record.id, (r) => {
        if (r.status !== 'running') return;
        r.status = 'failed';
        r.finishedAt = this.now().toISOString();
        r.error = 'Interrupted: the manager process stopped while this operation was running.';
        r.log.push(`[${this.now().toISOString()}] --- interrupted by manager restart ---`);
      });
      recovered++;
    }
    return recovered;
  }

  /** Newest-first operation list, optionally filtered by instance. */
  async list(filter?: { instanceId?: string; limit?: number }): Promise<OperationRecord[]> {
    let names: string[];
    try {
      names = await readdir(this.dir);
    } catch {
      return [];
    }
    const records: OperationRecord[] = [];
    for (const name of names) {
      if (!name.endsWith('.json')) continue;
      try {
        const record = JSON.parse(await readFile(path.join(this.dir, name), 'utf8')) as OperationRecord;
        if (filter?.instanceId !== undefined && record.instanceId !== filter.instanceId) continue;
        records.push(record);
      } catch {
        // Half-written/corrupt journal entry: skip rather than break the list.
      }
    }
    records.sort((a, b) => b.startedAt.localeCompare(a.startedAt));
    return records.slice(0, filter?.limit ?? 100);
  }
}

/** Append-only JSONL audit log of every operator-visible action. */
export class AuditLog {
  private readonly file: string;
  private readonly now: () => Date;

  constructor(root: string, now: () => Date = () => new Date()) {
    this.file = path.join(managerStateDir(root), 'audit.jsonl');
    this.now = now;
  }

  async record(entry: Omit<AuditEntry, 'at'>): Promise<void> {
    await mkdir(path.dirname(this.file), { recursive: true });
    const full: AuditEntry = { at: this.now().toISOString(), ...entry };
    await appendFile(this.file, JSON.stringify(redactObject(full)) + '\n', 'utf8');
  }

  /** Newest-first tail of the audit log (for the GUI). */
  async tail(limit = 200): Promise<AuditEntry[]> {
    let raw: string;
    try {
      raw = await readFile(this.file, 'utf8');
    } catch {
      return [];
    }
    const lines = raw.split('\n').filter((l) => l.trim() !== '');
    const out: AuditEntry[] = [];
    for (const line of lines.slice(-limit)) {
      try {
        out.push(JSON.parse(line) as AuditEntry);
      } catch {
        // Skip torn lines (crash mid-append); the log stays readable.
      }
    }
    return out.reverse();
  }
}

export class InstanceLockedError extends Error {
  constructor(
    public readonly instanceId: string,
    public readonly holder: { operationId: string; acquiredAt: string },
  ) {
    super(
      `Instance "${instanceId}" is busy: operation ${holder.operationId} has been running since ${holder.acquiredAt}. ` +
        'One mutating operation per instance at a time.',
    );
    this.name = 'InstanceLockedError';
  }
}

interface LockFilePayload {
  operationId: string;
  pid: number;
  acquiredAt: string;
}

/**
 * Per-instance mutating-operation lock, backed by exclusive-create lockfiles.
 * Stale locks (their pid no longer alive) are stolen with a log trail; locks
 * from the CURRENT process are never considered stale.
 */
export class InstanceLocks {
  private readonly dir: string;
  private readonly now: () => Date;

  constructor(root: string, now: () => Date = () => new Date()) {
    this.dir = path.join(managerStateDir(root), 'locks');
    this.now = now;
  }

  private file(instanceId: string): string {
    // Lowercase only (mirrors the BFF route guard): uppercase ids are never
    // produced by the CLI and on case-insensitive filesystems "A" and "a"
    // would collide into the same lockfile.
    if (!/^[a-z0-9][a-z0-9-]*$/.test(instanceId)) throw new Error(`Invalid instance id "${instanceId}".`);
    return path.join(this.dir, `${instanceId}.lock`);
  }

  private async readHolder(instanceId: string): Promise<LockFilePayload | null> {
    try {
      return JSON.parse(await readFile(this.file(instanceId), 'utf8')) as LockFilePayload;
    } catch {
      return null;
    }
  }

  private static pidAlive(pid: number): boolean {
    try {
      process.kill(pid, 0);
      return true;
    } catch {
      return false;
    }
  }

  async acquire(instanceId: string, operationId: string): Promise<{ release: () => Promise<void> }> {
    await mkdir(this.dir, { recursive: true });
    const payload: LockFilePayload = { operationId, pid: process.pid, acquiredAt: this.now().toISOString() };
    const attempt = async (): Promise<boolean> => {
      try {
        await writeFile(this.file(instanceId), JSON.stringify(payload), { flag: 'wx' });
        return true;
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'EEXIST') throw err;
        return false;
      }
    };

    if (!(await attempt())) {
      const holder = await this.readHolder(instanceId);
      // A crashed manager leaves its lockfile behind; a lock whose pid is no
      // longer alive cannot be protecting anything, so steal it. A lock held
      // by THIS process is always genuinely busy.
      const stale = holder !== null && holder.pid !== process.pid && !InstanceLocks.pidAlive(holder.pid);
      if (!stale) {
        throw new InstanceLockedError(instanceId, {
          operationId: holder?.operationId ?? 'unknown',
          acquiredAt: holder?.acquiredAt ?? 'unknown',
        });
      }
      await rm(this.file(instanceId), { force: true });
      if (!(await attempt())) {
        const racer = await this.readHolder(instanceId);
        throw new InstanceLockedError(instanceId, {
          operationId: racer?.operationId ?? 'unknown',
          acquiredAt: racer?.acquiredAt ?? 'unknown',
        });
      }
    }

    return {
      release: async () => {
        // Only remove our own lock (a stale-steal may have replaced it).
        const current = await this.readHolder(instanceId);
        if (current?.operationId === operationId) await rm(this.file(instanceId), { force: true });
      },
    };
  }

  async holder(instanceId: string): Promise<LockFilePayload | null> {
    const holder = await this.readHolder(instanceId);
    if (holder === null) return null;
    // A lock whose owning process is gone is a crash leftover. Report the
    // instance as free (acquire() steals such locks the same way) so the GUI
    // doesn't show it busy forever, and clean the file up best-effort.
    if (holder.pid !== process.pid && !InstanceLocks.pidAlive(holder.pid)) {
      await rm(this.file(instanceId), { force: true });
      return null;
    }
    return holder;
  }
}

/** Context handed to the operation body for progress reporting. */
export interface OperationContext {
  operationId: string;
  log(line: string): Promise<void>;
  setPhase(phase: string): Promise<void>;
}

export interface StartOperationOptions {
  kind: OperationKind;
  /** Lock target; null runs without a per-instance lock (server-level work). */
  instanceId: string | null;
  operator: string;
  sourceIp: string | null;
  /** Audit action name, defaults to the kind. */
  action?: string;
}

/**
 * Runs operations through journal + audit + per-instance lock. `start()`
 * resolves with the operation id as soon as the lock is held and the journal
 * row exists; the body keeps running in the background (HTTP 202 semantics).
 */
export class OperationRunner {
  constructor(
    private readonly journal: OperationJournal,
    private readonly audit: AuditLog,
    private readonly locks: InstanceLocks,
  ) {}

  async start(
    opts: StartOperationOptions,
    body: (ctx: OperationContext) => Promise<unknown>,
  ): Promise<{ operationId: string; done: Promise<void> }> {
    const action = opts.action ?? opts.kind;
    const record = await this.journal.create(opts.kind, opts.instanceId);

    let lock: { release: () => Promise<void> } | null = null;
    if (opts.instanceId !== null) {
      try {
        lock = await this.locks.acquire(opts.instanceId, record.id);
      } catch (err) {
        await this.journal.fail(record.id, err);
        await this.audit.record({
          operator: opts.operator,
          action,
          instanceId: opts.instanceId,
          operationId: record.id,
          sourceIp: opts.sourceIp,
          result: 'denied',
          detail: err instanceof Error ? err.message : String(err),
        });
        throw err;
      }
    }

    await this.audit.record({
      operator: opts.operator,
      action,
      instanceId: opts.instanceId,
      operationId: record.id,
      sourceIp: opts.sourceIp,
      result: 'started',
    });

    const ctx: OperationContext = {
      operationId: record.id,
      log: (line) => this.journal.append(record.id, line),
      setPhase: (phase) => this.journal.setPhase(record.id, phase),
    };

    const done = (async () => {
      try {
        const result = await body(ctx);
        await this.journal.complete(record.id, result);
        await this.audit.record({
          operator: opts.operator,
          action,
          instanceId: opts.instanceId,
          operationId: record.id,
          sourceIp: opts.sourceIp,
          result: 'succeeded',
        });
      } catch (err) {
        await this.journal.fail(record.id, err);
        await this.audit.record({
          operator: opts.operator,
          action,
          instanceId: opts.instanceId,
          operationId: record.id,
          sourceIp: opts.sourceIp,
          result: 'failed',
          detail: err instanceof Error ? err.message : String(err),
        });
      } finally {
        if (lock) await lock.release();
      }
    })();

    return { operationId: record.id, done };
  }
}
