// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
/**
 * Bootstrap wizard state machine (pure).
 *
 * Models the first-server bootstrap flow as an ordered list of steps with
 * collected answers and recorded environment-check results. It performs NO
 * side effects: the HTTP layer runs the actual checks (Docker, internet,
 * registry signature, resource preflight, install, health) and feeds the
 * results back in via {@link recordCheck}. Progression is gated so an operator
 * cannot skip past a failed mandatory check, and `buildBootstrapPlan` turns the
 * validated answers into the exact `server init` + `instance install` calls the
 * executor runs.
 *
 * No secret ever flows through here: the admin password is generated by the
 * installer and shown once; it is never part of the wizard config or plan.
 */
import type { InstanceMode, ReleaseChannel } from '@shm/schemas';

/** Ordered bootstrap steps. */
export const WIZARD_STEPS = [
  'welcome',
  'docker',
  'internet',
  'registry',
  'install_root',
  'resources',
  'mode',
  'domain',
  'proxy',
  'instance',
  'admin',
  'install',
  'health',
  'done',
] as const;

export type WizardStepId = (typeof WIZARD_STEPS)[number];

/** Steps whose progression is gated by a recorded environment-check result. */
const CHECK_STEPS: ReadonlySet<WizardStepId> = new Set<WizardStepId>([
  'docker',
  'internet',
  'registry',
  'resources',
  'install',
  'health',
]);

export type CheckSeverity = 'ok' | 'warning' | 'error';

export interface CheckResult {
  ok: boolean;
  severity: CheckSeverity;
  detail?: string;
}

export interface WizardConfig {
  root: string;
  serverId: string;
  mode: InstanceMode;
  domain?: string;
  localPort?: number;
  letsencryptEmail?: string;
  registryUrl: string;
  channel: ReleaseChannel;
  version: string;
  instanceId: string;
  instanceName: string;
  adminEmail?: string;
  adminName?: string;
}

export interface WizardState {
  steps: readonly WizardStepId[];
  stepIndex: number;
  config: WizardConfig;
  checks: Partial<Record<WizardStepId, CheckResult>>;
  /** Set once the install + health steps have succeeded. */
  completed: boolean;
}

export const DEFAULT_REGISTRY_URL = 'https://humdek-unibe-ch.github.io/sh2-plugin-registry/';

function defaultConfig(): WizardConfig {
  return {
    root: '/opt/selfhelp',
    serverId: '',
    mode: 'production',
    registryUrl: DEFAULT_REGISTRY_URL,
    channel: 'stable',
    version: 'latest',
    instanceId: '',
    instanceName: '',
  };
}

export function initWizard(partial?: Partial<WizardConfig>): WizardState {
  return {
    steps: WIZARD_STEPS,
    stepIndex: 0,
    config: { ...defaultConfig(), ...partial },
    checks: {},
    completed: false,
  };
}

export function currentStep(state: WizardState): WizardStepId {
  const step = state.steps[state.stepIndex];
  // Index is always clamped by advance/back, so this is defensive only.
  return step ?? 'done';
}

export function setConfig(state: WizardState, partial: Partial<WizardConfig>): WizardState {
  return { ...state, config: { ...state.config, ...partial } };
}

export function recordCheck(state: WizardState, step: WizardStepId, result: CheckResult): WizardState {
  return { ...state, checks: { ...state.checks, [step]: result } };
}

const INSTANCE_ID_RE = /^[a-z][a-z0-9-]{1,38}[a-z0-9]$/;
const HOSTNAME_RE = /^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i;
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/**
 * Per-step answer validation. Returns the list of blocking problems for the
 * answers a given step collects (empty = the step's answers are valid).
 */
export function validateStep(step: WizardStepId, config: WizardConfig): string[] {
  const errors: string[] = [];
  switch (step) {
    case 'install_root':
      if (!config.root.trim()) errors.push('Install root is required.');
      break;
    case 'mode':
      if (config.mode !== 'production' && config.mode !== 'local') errors.push('Mode must be production or local.');
      if (!config.serverId.trim()) errors.push('Server id is required.');
      break;
    case 'domain':
      if (config.mode === 'production') {
        if (!config.domain || !HOSTNAME_RE.test(config.domain)) {
          errors.push('A valid public domain is required for production installs.');
        }
        if (config.letsencryptEmail && !EMAIL_RE.test(config.letsencryptEmail)) {
          errors.push("Let's Encrypt email is invalid.");
        }
      } else {
        if (config.localPort === undefined || !Number.isInteger(config.localPort) || config.localPort < 1 || config.localPort > 65535) {
          errors.push('A valid localhost port (1-65535) is required for local installs.');
        }
      }
      break;
    case 'instance':
      if (!INSTANCE_ID_RE.test(config.instanceId)) {
        errors.push('Instance id must be lowercase letters, digits and hyphens (3-40 chars).');
      }
      if (!config.instanceName.trim()) errors.push('Instance display name is required.');
      if (!/^https?:\/\//.test(config.registryUrl)) errors.push('Registry URL must be http(s).');
      break;
    case 'admin':
      // Admin is optional (operator may create the admin out-of-band), but a
      // supplied email must be valid. The password is generated, never entered.
      if (config.adminEmail && !EMAIL_RE.test(config.adminEmail)) errors.push('Admin email is invalid.');
      break;
    default:
      break;
  }
  return errors;
}

export interface AdvanceDecision {
  ok: boolean;
  reason?: string;
}

/** Whether the wizard may move on from the current step. */
export function canAdvance(state: WizardState): AdvanceDecision {
  const step = currentStep(state);
  if (step === 'done') return { ok: false, reason: 'Wizard is already at the final step.' };

  if (CHECK_STEPS.has(step)) {
    const result = state.checks[step];
    if (!result) return { ok: false, reason: `The ${step} check has not run yet.` };
    if (result.severity === 'error' || !result.ok) {
      return { ok: false, reason: result.detail ?? `The ${step} check failed.` };
    }
    return { ok: true };
  }

  const errors = validateStep(step, state.config);
  if (errors.length > 0) return { ok: false, reason: errors.join(' ') };
  return { ok: true };
}

export function advance(state: WizardState): WizardState {
  const decision = canAdvance(state);
  if (!decision.ok) throw new WizardError(decision.reason ?? 'Cannot advance.');
  const nextIndex = Math.min(state.stepIndex + 1, state.steps.length - 1);
  let next: WizardState = { ...state, stepIndex: nextIndex };
  if (currentStep(next) === 'done') next = { ...next, completed: true };
  return next;
}

export function back(state: WizardState): WizardState {
  return { ...state, stepIndex: Math.max(state.stepIndex - 1, 0) };
}

export function isBootstrapComplete(state: WizardState): boolean {
  return state.completed || currentStep(state) === 'done';
}

export class WizardError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WizardError';
  }
}

export interface ServerInitPlan {
  serverId: string;
  mode: InstanceMode;
  letsencryptEmail?: string;
  /**
   * Set on the retry path: a failed first attempt leaves the server partly
   * bootstrapped (inventory + proxy + instance dir on disk), so the re-run must
   * acknowledge import/repair instead of refusing with a bootstrap conflict.
   */
  allowImport?: boolean;
}

export interface InstanceInstallPlan {
  instanceId: string;
  displayName: string;
  mode: InstanceMode;
  domain?: string;
  localPort?: number;
  registryUrl: string;
  channel: ReleaseChannel;
  version: string;
  bringUp: true;
  provision: true;
  adminEmail?: string;
  adminName?: string;
}

export interface BootstrapPlan {
  root: string;
  serverInit: ServerInitPlan;
  instanceInstall: InstanceInstallPlan;
}

/** Validate the whole config across the steps that collect answers. */
export function validateConfig(config: WizardConfig): string[] {
  const steps: WizardStepId[] = ['install_root', 'mode', 'domain', 'instance', 'admin'];
  return steps.flatMap((s) => validateStep(s, config));
}

/**
 * Turn validated answers into the concrete executor calls. Throws
 * {@link WizardError} if the config is incomplete/invalid. The plan NEVER
 * carries secrets — the admin password is generated by the installer.
 */
export function buildBootstrapPlan(config: WizardConfig): BootstrapPlan {
  const errors = validateConfig(config);
  if (errors.length > 0) throw new WizardError(`Invalid bootstrap config: ${errors.join(' ')}`);

  const serverInit: ServerInitPlan = {
    serverId: config.serverId,
    mode: config.mode,
    ...(config.mode === 'production' && config.letsencryptEmail ? { letsencryptEmail: config.letsencryptEmail } : {}),
  };

  const instanceInstall: InstanceInstallPlan = {
    instanceId: config.instanceId,
    displayName: config.instanceName,
    mode: config.mode,
    ...(config.mode === 'production' ? { domain: config.domain } : { localPort: config.localPort }),
    registryUrl: config.registryUrl,
    channel: config.channel,
    version: config.version,
    bringUp: true,
    provision: true,
    ...(config.adminEmail ? { adminEmail: config.adminEmail, adminName: config.adminName ?? 'Admin' } : {}),
  };

  return { root: config.root, serverInit, instanceInstall };
}
