// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
import { describe, expect, it } from 'vitest';
import type { InstanceLock, InstanceManifest } from '@shm/schemas';
import { REDACTED, findResidualSecrets, redactEnv, redactObject, redactString } from './redact.js';
import { assembleSupportBundle } from './bundle.js';

describe('redactString', () => {
  it('redacts env-style secret assignments', () => {
    expect(redactString('APP_SECRET=supersecret')).toBe(`APP_SECRET=${REDACTED}`);
    expect(redactString('DB_PASSWORD: hunter2')).toBe(`DB_PASSWORD: ${REDACTED}`);
  });

  it('redacts DB URL credentials but keeps the host', () => {
    const out = redactString('DATABASE_URL=mysql://app:secretpw@db:3306/selfhelp');
    expect(out).not.toContain('secretpw');
    expect(out).toContain('@db:3306/selfhelp');
  });

  it('redacts PEM private keys', () => {
    const pem = '-----BEGIN PRIVATE KEY-----\nabcDEF123\n-----END PRIVATE KEY-----';
    expect(redactString(pem)).toBe(REDACTED);
    expect(findResidualSecrets(redactString(pem))).toHaveLength(0);
  });

  it('redacts every value in a generated instance secrets.env (no raw secret survives)', () => {
    // Mirrors the shape emitted by @shm/instances secretEnvMap + the JWT keypair.
    const secretsEnv = [
      '# Generated by SelfHelp Manager. SECRET runtime config (0600, per-instance).',
      'APP_SECRET=RAWAPPSECRET',
      'DATABASE_URL=mysql://selfhelp:RAWDBPW@mysql:3306/selfhelp?serverVersion=8.4',
      'MYSQL_PASSWORD=RAWDBPW',
      'MYSQL_ROOT_PASSWORD=RAWROOTPW',
      'REDIS_PASSWORD=RAWREDISPW',
      'REDIS_URL=redis://default:RAWREDISPW@redis:6379',
      'MERCURE_JWT_SECRET=RAWMERCURE',
      'MERCURE_PUBLISHER_JWT_KEY=RAWMERCURE',
      'JWT_PASSPHRASE=RAWPASSPHRASE',
      '-----BEGIN ENCRYPTED PRIVATE KEY-----',
      'RAWPRIVATEKEYMATERIAL',
      '-----END ENCRYPTED PRIVATE KEY-----',
    ].join('\n');

    const redacted = redactString(secretsEnv);
    for (const raw of ['RAWAPPSECRET', 'RAWDBPW', 'RAWROOTPW', 'RAWREDISPW', 'RAWMERCURE', 'RAWPASSPHRASE', 'RAWPRIVATEKEYMATERIAL']) {
      expect(redacted).not.toContain(raw);
    }
    expect(findResidualSecrets(redacted)).toHaveLength(0);
  });
});

describe('redactObject / redactEnv', () => {
  it('redacts by secret key name', () => {
    const out = redactObject({ APP_SECRET: 'x', nested: { jwtPrivateKey: 'y', safe: 'ok' } }) as Record<string, unknown>;
    expect(out.APP_SECRET).toBe(REDACTED);
    expect((out.nested as Record<string, unknown>).jwtPrivateKey).toBe(REDACTED);
    expect((out.nested as Record<string, unknown>).safe).toBe('ok');
  });

  it('redacts an env map', () => {
    const env = redactEnv({ APP_SECRET: 'x', NEXT_PUBLIC_API_URL: '/api' });
    expect(env.APP_SECRET).toBe(REDACTED);
    expect(env.NEXT_PUBLIC_API_URL).toBe('/api');
  });
});

const manifest = { manifestVersion: 1, instanceId: 'website1' } as unknown as InstanceManifest;
const lock = { lockfileVersion: 1 } as unknown as InstanceLock;

describe('assembleSupportBundle', () => {
  const bundle = assembleSupportBundle({
    instanceId: 'website1',
    managerVersion: '0.1.0',
    schemaVersions: { manifest: 1, lock: 1 },
    manifest,
    lock,
    versionSummary: { selfhelp: '1.4.2' },
    installedPlugins: [{ id: 'survey-js', version: '1.3.0' }],
    env: { APP_SECRET: 'topsecret', NEXT_PUBLIC_API_URL: '/api' },
    healthResults: { backend: 'ok' },
    composeStatus: 'running',
    logs: { backend: 'DATABASE_URL=mysql://app:pw@db/selfhelp\nstarting...' },
  });

  it('marks redaction applied and lists contents', () => {
    expect(bundle.meta.redactionApplied).toBe(true);
    expect(bundle.meta.contents).toContain('manifest.json');
  });

  it('contains no secrets', () => {
    const all = bundle.files.map((f) => f.content).join('\n');
    expect(all).not.toContain('topsecret');
    expect(all).not.toContain(':pw@');
    expect(all).toContain(REDACTED);
  });
});
