// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
/**
 * Wrapper-script generation (`sh-manager wrapper`).
 *
 * The published image is the recommended way to run the manager, but every
 * invocation needs the same `docker run` plumbing (socket mount, state mount,
 * GUI port publishing). This command prints a tiny `shm` wrapper script so the
 * image itself distributes its own convenience layer:
 *
 *   docker run --rm ghcr.io/…/sh-manager:latest wrapper --shell powershell > shm.ps1
 *
 * The script's state folder is, by default, the folder the script is saved in
 * ("save it into your state folder"), so calls work from anywhere without the
 * fresh-root surprises a cwd-based wrapper would have. Engine-side path
 * translation happens inside the manager (see @shm/docker host-paths); the
 * wrapper stays dumb on purpose.
 */
import { MANAGER_IMAGE } from './self-update.js';

export type WrapperShell = 'powershell' | 'bash';

export interface WrapperOptions {
  shell: WrapperShell;
  /** Bake an explicit state folder; default: the folder containing the script. */
  root?: string;
  /** Manager image reference (default: the official `:latest`). */
  image?: string;
  /** Published localhost port for `shm web` (default 8765). */
  webPort?: number;
}

const DEFAULT_WEB_PORT = 8765;

function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function powershellScript(image: string, root: string | undefined, webPort: number): string {
  const rootLine = root ? `$Root = ${psQuote(root)}` : '$Root = $PSScriptRoot';
  return `# shm.ps1 - SelfHelp Manager wrapper (generated by: sh-manager wrapper --shell powershell)
# State folder: ${root ? root : 'the folder containing this script'} - keep this file in your
# SelfHelp state folder (e.g. D:\\selfhelp); you can then call it from anywhere.
# Every call runs the manager image with the Docker socket + state folder
# mounted; \`.\\shm.ps1 web\` also publishes the GUI on http://127.0.0.1:${webPort}.
$ErrorActionPreference = 'Stop'
$Image = ${psQuote(image)}
${rootLine}
$WebPort = ${webPort}
$DockerArgs = @(
  'run', '--rm',
  '--add-host=host.docker.internal:host-gateway',
  '-v', '/var/run/docker.sock:/var/run/docker.sock',
  '-v', "\${Root}:/opt/selfhelp"
)
# Recognisable container names: the GUI is the single long-running container
# ("name already in use" means it is already running - docker rm -f sh-manager-web);
# one-shot CLI calls get a per-shell suffix so parallel shells never collide.
if ($args.Count -gt 0 -and $args[0] -eq 'web') {
  $Rest = @($args | Select-Object -Skip 1)
  docker @DockerArgs --name sh-manager-web -p "127.0.0.1:\${WebPort}:\${WebPort}" $Image web --host 0.0.0.0 --port $WebPort @Rest
} else {
  docker @DockerArgs --name "sh-manager-cli-$PID" $Image @args
}
exit $LASTEXITCODE
`;
}

function bashScript(image: string, root: string | undefined, webPort: number): string {
  const rootLine = root
    ? `ROOT=${shQuote(root)}`
    : `ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"`;
  return `#!/usr/bin/env bash
# shm.sh - SelfHelp Manager wrapper (generated by: sh-manager wrapper --shell bash)
# State folder: ${root ? root : 'the folder containing this script'} - keep this file in your
# SelfHelp state folder (e.g. /opt/selfhelp); you can then call it from anywhere.
# Every call runs the manager image with the Docker socket + state folder
# mounted; \`./shm.sh web\` also publishes the GUI on http://127.0.0.1:${webPort}.
set -euo pipefail
IMAGE=${shQuote(image)}
${rootLine}
WEB_PORT=${webPort}
# Git Bash (MSYS): hand Docker a real Windows path and stop MSYS from
# rewriting the -v arguments. Both lines are no-ops on Linux/macOS.
if command -v cygpath >/dev/null 2>&1; then ROOT="$(cygpath -w "$ROOT")"; fi
export MSYS_NO_PATHCONV=1
DOCKER_ARGS=(run --rm
  --add-host=host.docker.internal:host-gateway
  -v /var/run/docker.sock:/var/run/docker.sock
  -v "$ROOT:/opt/selfhelp")
# Recognisable container names: the GUI is the single long-running container
# ("name already in use" means it is already running - docker rm -f sh-manager-web);
# one-shot CLI calls get a per-shell suffix so parallel shells never collide.
if [ "\${1:-}" = 'web' ]; then
  shift
  exec docker "\${DOCKER_ARGS[@]}" --name sh-manager-web -p "127.0.0.1:\${WEB_PORT}:\${WEB_PORT}" "$IMAGE" web --host 0.0.0.0 --port "$WEB_PORT" "$@"
fi
exec docker "\${DOCKER_ARGS[@]}" --name "sh-manager-cli-$$" "$IMAGE" "$@"
`;
}

/** Renders the wrapper script for the requested shell (stdout-ready). */
export function generateWrapperScript(opts: WrapperOptions): string {
  const image = opts.image ?? `${MANAGER_IMAGE}:latest`;
  const webPort = opts.webPort ?? DEFAULT_WEB_PORT;
  if (!Number.isInteger(webPort) || webPort <= 0 || webPort > 65535) {
    throw new Error(`Invalid web port: ${String(opts.webPort)}`);
  }
  switch (opts.shell) {
    case 'powershell':
      return powershellScript(image, opts.root, webPort);
    case 'bash':
      return bashScript(image, opts.root, webPort);
    default:
      throw new Error(`Unknown shell "${String(opts.shell)}" (use powershell or bash).`);
  }
}
