// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
/**
 * Wrapper-script generation (`sh-manager wrapper`).
 *
 * The published image is the recommended way to run the manager, but every
 * invocation needs the same `docker run` plumbing (socket mount, state mount,
 * GUI port publishing). This command prints a tiny `shm` wrapper script so the
 * image itself distributes its own convenience layer:
 *
 *   docker run --rm ghcr.io/…/sh-manager:latest wrapper --shell powershell > shm.ps1
 *
 * The script's state folder is, by default, the folder the script is saved in
 * ("save it into your state folder"), so calls work from anywhere without the
 * fresh-root surprises a cwd-based wrapper would have. Engine-side path
 * translation happens inside the manager (see @shm/docker host-paths); the
 * wrapper stays dumb on purpose.
 */
import { MANAGER_IMAGE } from './self-update.js';

export type WrapperShell = 'powershell' | 'bash';

export interface WrapperOptions {
  shell: WrapperShell;
  /** Bake an explicit state folder; default: the folder containing the script. */
  root?: string;
  /** Manager image reference (default: the official `:latest`). */
  image?: string;
  /** Published localhost port for `shm web` (default 8765). */
  webPort?: number;
}

const DEFAULT_WEB_PORT = 8765;

function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function powershellScript(image: string, root: string | undefined, webPort: number): string {
  const rootLine = root ? `$Root = ${psQuote(root)}` : '$Root = $PSScriptRoot';
  return `# shm.ps1 - SelfHelp Manager wrapper (generated by: sh-manager wrapper --shell powershell)
# State folder: ${root ? root : 'the folder containing this script'} - keep this file in your
# SelfHelp state folder (e.g. D:\\selfhelp); you can then call it from anywhere.
# Every call runs the manager image with the Docker socket + state folder mounted.
#
# Manager lifecycle:
#   .\\shm.ps1 up          start the web GUI in the background (http://127.0.0.1:${webPort})
#   .\\shm.ps1 down        stop + remove the web GUI container (instances keep running)
#   .\\shm.ps1 update      self-update: pull the new image + restart the GUI on it
#   .\\shm.ps1 reinstall   down + pull the image fresh + up
#   .\\shm.ps1 web         run the GUI in the foreground (Ctrl-C stops it)
#   anything else is passed to the sh-manager CLI (e.g. .\\shm.ps1 server status)
$ErrorActionPreference = 'Stop'
$Image = ${psQuote(image)}
${rootLine}
$WebPort = ${webPort}
$DockerArgs = @(
  'run', '--rm',
  '--add-host=host.docker.internal:host-gateway',
  '-v', '/var/run/docker.sock:/var/run/docker.sock',
  '-v', "\${Root}:/opt/selfhelp"
)
# Forgive a pasted leading 'sh-manager' token (the image entrypoint already IS
# the manager): .\\shm.ps1 sh-manager web behaves like .\\shm.ps1 web.
$CliArgs = @($args)
if ($CliArgs.Count -gt 0 -and $CliArgs[0] -eq 'sh-manager') {
  $CliArgs = @($CliArgs | Select-Object -Skip 1)
}
$Verb = if ($CliArgs.Count -gt 0) { $CliArgs[0] } else { '' }
$Rest = @($CliArgs | Select-Object -Skip 1)

function Stop-ManagerWeb {
  & docker rm -f sh-manager-web 2>$null | Out-Null
  $global:LASTEXITCODE = 0
}

# Recognisable container names: the GUI is the single long-running container;
# one-shot CLI calls get a per-shell suffix so parallel shells never collide.
switch ($Verb) {
  'down' {
    Stop-ManagerWeb
    Write-Host 'Manager web GUI stopped (sh-manager-web removed). Instances keep running.'
  }
  'reinstall' {
    Stop-ManagerWeb
    docker pull $Image
    docker @DockerArgs -d --name sh-manager-web -p "127.0.0.1:\${WebPort}:\${WebPort}" $Image web --host 0.0.0.0 --port $WebPort @Rest | Out-Null
    Write-Host "Manager reinstalled and running at http://127.0.0.1:\${WebPort} (it reconnects to existing instances automatically)."
  }
  'up' {
    Stop-ManagerWeb
    docker @DockerArgs -d --name sh-manager-web -p "127.0.0.1:\${WebPort}:\${WebPort}" $Image web --host 0.0.0.0 --port $WebPort @Rest | Out-Null
    Write-Host "Manager web GUI running at http://127.0.0.1:\${WebPort}"
  }
  'update' {
    docker @DockerArgs --name "sh-manager-cli-$PID" $Image self-update
  }
  'web' {
    docker @DockerArgs --name sh-manager-web -p "127.0.0.1:\${WebPort}:\${WebPort}" $Image web --host 0.0.0.0 --port $WebPort @Rest
  }
  default {
    docker @DockerArgs --name "sh-manager-cli-$PID" $Image @CliArgs
  }
}
exit $LASTEXITCODE
`;
}

function bashScript(image: string, root: string | undefined, webPort: number): string {
  const rootLine = root
    ? `ROOT=${shQuote(root)}`
    : `ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"`;
  return `#!/usr/bin/env bash
# shm.sh - SelfHelp Manager wrapper (generated by: sh-manager wrapper --shell bash)
# State folder: ${root ? root : 'the folder containing this script'} - keep this file in your
# SelfHelp state folder (e.g. /opt/selfhelp); you can then call it from anywhere.
# Every call runs the manager image with the Docker socket + state folder mounted.
#
# Manager lifecycle:
#   ./shm.sh up          start the web GUI in the background (http://127.0.0.1:${webPort})
#   ./shm.sh down        stop + remove the web GUI container (instances keep running)
#   ./shm.sh update      self-update: pull the new image + restart the GUI on it
#   ./shm.sh reinstall   down + pull the image fresh + up
#   ./shm.sh web         run the GUI in the foreground (Ctrl-C stops it)
#   anything else is passed to the sh-manager CLI (e.g. ./shm.sh server status)
set -euo pipefail
IMAGE=${shQuote(image)}
${rootLine}
WEB_PORT=${webPort}
# Git Bash (MSYS): hand Docker a real Windows path and stop MSYS from
# rewriting the -v arguments. Both lines are no-ops on Linux/macOS.
if command -v cygpath >/dev/null 2>&1; then ROOT="$(cygpath -w "$ROOT")"; fi
export MSYS_NO_PATHCONV=1
DOCKER_ARGS=(run --rm
  --add-host=host.docker.internal:host-gateway
  -v /var/run/docker.sock:/var/run/docker.sock
  -v "$ROOT:/opt/selfhelp")
# Forgive a pasted leading 'sh-manager' token (the image entrypoint already IS
# the manager): ./shm.sh sh-manager web behaves like ./shm.sh web.
if [ "\${1:-}" = 'sh-manager' ]; then shift; fi
stop_web() { docker rm -f sh-manager-web >/dev/null 2>&1 || true; }
start_web_detached() {
  docker "\${DOCKER_ARGS[@]}" -d --name sh-manager-web -p "127.0.0.1:\${WEB_PORT}:\${WEB_PORT}" "$IMAGE" web --host 0.0.0.0 --port "$WEB_PORT" "$@" >/dev/null
}
# Recognisable container names: the GUI is the single long-running container;
# one-shot CLI calls get a per-shell suffix so parallel shells never collide.
case "\${1:-}" in
  down)
    stop_web
    echo 'Manager web GUI stopped (sh-manager-web removed). Instances keep running.'
    ;;
  reinstall)
    shift
    stop_web
    docker pull "$IMAGE"
    start_web_detached "$@"
    echo "Manager reinstalled and running at http://127.0.0.1:\${WEB_PORT} (it reconnects to existing instances automatically)."
    ;;
  up)
    shift
    stop_web
    start_web_detached "$@"
    echo "Manager web GUI running at http://127.0.0.1:\${WEB_PORT}"
    ;;
  update)
    exec docker "\${DOCKER_ARGS[@]}" --name "sh-manager-cli-$$" "$IMAGE" self-update
    ;;
  web)
    shift
    exec docker "\${DOCKER_ARGS[@]}" --name sh-manager-web -p "127.0.0.1:\${WEB_PORT}:\${WEB_PORT}" "$IMAGE" web --host 0.0.0.0 --port "$WEB_PORT" "$@"
    ;;
  *)
    exec docker "\${DOCKER_ARGS[@]}" --name "sh-manager-cli-$$" "$IMAGE" "$@"
    ;;
esac
`;
}

/** Renders the wrapper script for the requested shell (stdout-ready). */
export function generateWrapperScript(opts: WrapperOptions): string {
  const image = opts.image ?? `${MANAGER_IMAGE}:latest`;
  const webPort = opts.webPort ?? DEFAULT_WEB_PORT;
  if (!Number.isInteger(webPort) || webPort <= 0 || webPort > 65535) {
    throw new Error(`Invalid web port: ${String(opts.webPort)}`);
  }
  switch (opts.shell) {
    case 'powershell':
      return powershellScript(image, opts.root, webPort);
    case 'bash':
      return bashScript(image, opts.root, webPort);
    default:
      throw new Error(`Unknown shell "${String(opts.shell)}" (use powershell or bash).`);
  }
}
