// SPDX-FileCopyrightText: 2026 Humdek, University of Bern
// SPDX-License-Identifier: MPL-2.0
/**
 * Generated non-secret instance `.env` values.
 *
 * Enforces the must-not-break BFF URL invariant: browser traffic uses the
 * `/api` prefix, while server-side frontend code calls Symfony over the
 * internal Docker network. Operators never guess these values.
 */
import type { InstanceMode } from '@shm/schemas';

export const BACKEND_INTERNAL_PORT = 8080;
export const FRONTEND_INTERNAL_PORT = 3000;
export const DEFAULT_BROWSER_API_PREFIX = '/api';
export const DEFAULT_SYMFONY_API_PREFIX = '/cms-api/v1';

export interface InstanceEnvInput {
  instanceId: string;
  mode: InstanceMode;
  selfhelpVersion: string;
  /**
   * Version of the deployed frontend image. The backend cannot know which
   * frontend build is running, so the manager injects it; the CMS surfaces it
   * on the admin system page (`SELFHELP_FRONTEND_VERSION`, else "unknown").
   */
  frontendVersion: string;
  publicFrontendUrl: string;
  mercurePublicUrl: string;
  browserApiPrefix?: string;
  symfonyApiPrefix?: string;
  schedulerTickSeconds?: number;
}

export interface InstanceRouting {
  publicFrontendUrl: string;
  browserApiPrefix: string;
  internalSymfonyUrl: string;
  symfonyApiPrefix: string;
}

export function buildInstanceRouting(input: InstanceEnvInput): InstanceRouting {
  return {
    publicFrontendUrl: input.publicFrontendUrl,
    browserApiPrefix: input.browserApiPrefix ?? DEFAULT_BROWSER_API_PREFIX,
    internalSymfonyUrl: `http://backend:${BACKEND_INTERNAL_PORT}`,
    symfonyApiPrefix: input.symfonyApiPrefix ?? DEFAULT_SYMFONY_API_PREFIX,
  };
}

/** Builds the non-secret env map. Secrets live in restricted secret files. */
export function buildInstanceEnv(input: InstanceEnvInput): Record<string, string> {
  const routing = buildInstanceRouting(input);
  return {
    APP_ENV: 'prod',
    SELFHELP_INSTANCE_ID: input.instanceId,
    SELFHELP_MODE: input.mode,
    // The env names the backend actually reads (config/services.yaml):
    // SELFHELP_CMS_VERSION feeds plugin-compatibility checks + the version
    // summary; SELFHELP_FRONTEND_VERSION feeds the admin system page (it
    // reports "unknown" when unset, e.g. source/dev checkouts).
    SELFHELP_CMS_VERSION: input.selfhelpVersion,
    SELFHELP_FRONTEND_VERSION: input.frontendVersion,
    // Browser path (BFF). Never the internal URL.
    NEXT_PUBLIC_API_URL: routing.browserApiPrefix,
    // Server-side frontend -> Symfony over the internal Docker network.
    SYMFONY_INTERNAL_URL: routing.internalSymfonyUrl,
    SYMFONY_API_PREFIX: routing.symfonyApiPrefix,
    MERCURE_PUBLIC_URL: input.mercurePublicUrl,
    SCHEDULED_JOBS_TICK_SECONDS: String(input.schedulerTickSeconds ?? 60),
    // JWT key *paths* are not secret (the keys themselves live in ./secrets/jwt,
    // mounted read-only at /app/config/jwt). The passphrase is in secrets.env.
    JWT_SECRET_KEY: '/app/config/jwt/private.pem',
    JWT_PUBLIC_KEY: '/app/config/jwt/public.pem',
  };
}

export function renderDotEnv(env: Record<string, string>): string {
  const header =
    '# Generated by SelfHelp Manager. Non-secret runtime config only.\n' +
    '# Secrets live in ./secrets/ with restrictive permissions.\n';
  const lines = Object.entries(env).map(([k, v]) => `${k}=${v}`);
  return header + lines.join('\n') + '\n';
}
